{% set name = "xicam.core" %}
{% set version = "2.2.3" %}
{% set sha256 = "5BA075809AFFD62245004B64C57E78A19F715907C1A490AF4F0772F26A75D255" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/synchrotrons/Xi-cam.core/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: "python"
  script: "{{ PYTHON }} -m pip install . --no-deps -vv "

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - dask
    - databroker
    - distributed
    - pyqt >=5
    - qtpy

test:
  imports:
    - xicam.core
    - xicam.core.data
    - xicam.core.msg

about:
  home: "https://github.com/lbl-camera/Xi-cam.core"
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The CAMERA platform for synchrotron data management, visualization, and reduction.
  description: |
    The xicam.core package contains all backend code of the Xi-cam platform, as
    part of the xicam namespace package. For the gui components, see
    "xicam.gui".
